# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  check-pr-description:
    uses: ./.github/workflows/test.yml
    with:
      pr_number: ${{ github.ref_name.split('-').pop() }}
    secrets: inherit

