# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  get-pr-number:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        run: |
          echo ${REF_NAME##*-}
          echo "pr_number=${REF_NAME##*-}" >> $GITHUB_OUTPUT
        env:
          REF_NAME: ${{ github.ref_name }}
  
  check-pr-description:
    needs:
      - get-pr-number
    uses: ./.github/workflows/test.yml
    with:
      pr_number: ${{ needs.get-pr-number.outputs.pr_number }}
    secrets: inherit

