# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        run: |
          echo ${REF_NAME##*-}
          echo "pr_number=${REF_NAME##*-}" >> $GITHUB_OUTPUT
          echo "test=hello" >> $GITHUB_OUTPUT
        env:
          REF_NAME: ${{ github.ref_name }}
  
  check-pr-description:
    needs:
      - test1
    uses: ./.github/workflows/test.yml
    with:
      pr_number: ${{ needs.test1.outputs.test }}
    secrets: inherit

