name: Test
on:
  workflow_call:
    inputs:
      pr_number:
        description: PR Number
        type: string
        required: true

jobs:
  check_description:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          echo $PR_NUMBER
        env:
          PR_NUMBER: ${{ inputs.pr_number }}
