name: Test
on:
  workflow_call:
    inputs:
      ref_name:
        description: Ref name
        type: string
        required: true

jobs:
  check_description:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          PR_NUMBER=$(echo ${REF_NAME##*-})
          echo $PR_NUMBER
